//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyMeasure
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> Neck { get; set; }
        public Nullable<double> Shoulder { get; set; }
        public Nullable<double> Chest { get; set; }
        public Nullable<double> Biceps { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Hips { get; set; }
        public Nullable<double> Thigs { get; set; }
        public Nullable<double> Calves { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
    }
}
