//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExercisesAct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DescriptionURL { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> TargetRegionID { get; set; }
    }
}
