//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Calori { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Carbonhydrate { get; set; }
        public Nullable<double> Fat { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public Nullable<int> Gram { get; set; }
    }
}
