//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Xamarin_KURSATCAKAL_WebAPIEntities : DbContext
    {
        public Xamarin_KURSATCAKAL_WebAPIEntities()
            : base("name=Xamarin_KURSATCAKAL_WebAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyAnalizeResult> BodyAnalizeResult { get; set; }
        public virtual DbSet<BodyMeasure> BodyMeasure { get; set; }
        public virtual DbSet<BodyTypes> BodyTypes { get; set; }
        public virtual DbSet<CrashArea> CrashArea { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<ExercisesAct> ExercisesAct { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<MealTime> MealTime { get; set; }
        public virtual DbSet<NutrationProgram> NutrationProgram { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<SportProgram> SportProgram { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
