//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportProgram
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> ActID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string RepeatPercantage { get; set; }
    }
}
