//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_Admin_Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyMeasure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BodyMeasure()
        {
            this.BodyAnalizeResult = new HashSet<BodyAnalizeResult>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> Neck { get; set; }
        public Nullable<double> Shoulder { get; set; }
        public Nullable<double> Chest { get; set; }
        public Nullable<double> Biceps { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Hips { get; set; }
        public Nullable<double> Thigs { get; set; }
        public Nullable<double> Calves { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyAnalizeResult> BodyAnalizeResult { get; set; }
        public virtual User User { get; set; }
    }
}
