//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robolife_Admin_Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrationProgram
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> MealTimeID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> Gram { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual MealTime MealTime { get; set; }
        public virtual User User { get; set; }
    }
}
